### ISSUE TITLE
Reverting to previous shield will cause the ui to recognize current shield health as max health

### ISSUE THREAD

**Issue by bence056** [ThoughtOverflow/SnailReloaded#9]
https://github.com/ThoughtOverflow/SnailReloaded/blob/bca80add9f9e552c9b199b75a77ed89b34179fd6/Source/SnailReloaded/Private/Components/ArmoredHealthComponent.cpp#L122

This line runs the data update, but it also sets the current shield data structs CurrentHealth variable to the shield's health, causing the widget to display the incorrect value.

**Comment by Aby-409** [comment]
_Ok guys hear me out, enemy teams should be slugs._

**Comment by AnRichard03** [comment]
sNAIIIIIIIIIIIIIIIIIILLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
